# Generated by Django 5.0.14 on 2025-08-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('ITEM', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField(blank=True, null=True)),
                ('NombreTecnico', models.CharField(max_length=255)),
                ('Medida', models.CharField(blank=True, max_length=50, null=True)),
                ('UnidadMedida', models.CharField(blank=True, max_length=50, null=True)),
                ('Marca', models.CharField(blank=True, max_length=255, null=True)),
                ('Descripcion', models.TextField(blank=True, null=True)),
                ('Imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('Proveedor', models.IntegerField(blank=True, null=True)),
                ('Ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('Estado', models.CharField(blank=True, max_length=50, null=True)),
                ('Categoria', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
