# Generated by Django 5.0.14 on 2025-08-03 06:14

import inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_salidabodega_detallesalida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to=inventario.models.ruta_imagen_producto),
        ),
    ]
